apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tidi
  namespace: argocd
spec:
  description: Tidi Services Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: tidi
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'