apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-config
data:
  resolv.conf: |
    nameserver 10.96.0.10
    search staging.svc.cluster.local svc.cluster.local cluster.local invalid
    options ndots:5
    nameserver 8.8.8.8
    nameserver 8.8.4.4

