apiVersion: v1
kind: Service
metadata:
  name: {{ include "tidi-order.fullname" . }}
  labels:
    {{- include "tidi-order.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "tidi-order.selectorLabels" . | nindent 4 }}
